In [2]:
import numpy as np

In [8]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner/high-school-reunion/
dailywts = 185 - np.arange(35) / 5
print(dailywts.shape)
print(dailywts)

(35,)
[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [10]:
# avgwts = [0 for i in range(10)]
avgwts = [0, 0]
for i in range(0, 5):
    avgwts[0] += dailywts[i * 7 + 5]
    avgwts[1] += dailywts[i * 7 + 6]
avgwts[0] /= 5
avgwts[1] /= 5
print(avgwts)

[np.float64(181.2), np.float64(181.0)]


In [13]:
dailywts[5::7], dailywts[6::7]

(array([184. , 182.6, 181.2, 179.8, 178.4]),
 array([183.8, 182.4, 181. , 179.6, 178.2]))

In [14]:
(dailywts[5::7] + dailywts[6::7]) / 2

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [23]:
n, m = 2, 3
# arr = [[0 for i in range(m)] for j in range(n) ]
# print(arr)
arr = [[] for i in range(4)]
arr[0] = np.arange(1, 14, 2)
arr[1] = np.arange(17, 30, 2)
arr[2] = np.arange(33, 46, 2)
arr[3] = np.arange(49, 62, 2)
print(arr)

[array([ 1,  3,  5,  7,  9, 11, 13]), array([17, 19, 21, 23, 25, 27, 29]), array([33, 35, 37, 39, 41, 43, 45]), array([49, 51, 53, 55, 57, 59, 61])]


In [26]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/
arr = [[] for i in range(4)]
for i in range(0, 4):
    sbd = int((16 * i) + 1)
    skt = int(sbd + 13)
    arr[i] = np.arange(sbd, skt, 2)
print(arr)

[array([ 1,  3,  5,  7,  9, 11, 13]), array([17, 19, 21, 23, 25, 27, 29]), array([33, 35, 37, 39, 41, 43, 45]), array([49, 51, 53, 55, 57, 59, 61])]


In [47]:
arr1 = np.arange(1, 64, 2).reshape(4, -1)
arr2 = arr1[:, :-1]
print(arr2)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


In [60]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
print(gold)
print(np.unique(gold))

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]
[0 1 2 3 4 5 6 7 8 9]


In [68]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner/gold-miner/
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
print(gold)

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])


# Extract the values at the specific locations
values_at_locs = gold[locs[:, 0], locs[:, 1]]

print("\nValues at the specified locations:")
print(values_at_locs)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]

Values at the specified locations:
[2 6 2 8 2]


In [69]:
locs[:, 0], locs[:, 1]

(array([0, 2, 2, 5, 6]), array([4, 2, 3, 1, 3]))

In [89]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/
def make_roux(n):
    """returns a roux array of length n"""
    arr = [0] * n
    lastnum = (n + 1) // 2
    add_index = 1 if n % 2 == 0 else 0
    for i in range(0, lastnum):
        arr[2 * i + add_index] = ( (lastnum -i)) ** 2
       
    return arr
print(make_roux(5)) 
print(make_roux(8))
print(make_roux(12))


[9, 0, 4, 0, 1]
[0, 16, 0, 9, 0, 4, 0, 1]
[0, 36, 0, 25, 0, 16, 0, 9, 0, 4, 0, 1]


In [105]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner/chic-fil-a/
listabc1 = np.linspace(17, 28, 3)
listabc2 = np.linspace(32, 36, 3)
print(30 - listabc1[1])
print(abs(30 - listabc2[1]))

7.5
4.0


In [98]:
np.linspace(17, 28, 4)

array([17.        , 20.66666667, 24.33333333, 28.        ])

In [100]:
np.linspace(0, 9, 4)

array([0., 3., 6., 9.])

In [106]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/intermediate/love-distance/
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)

print(love_scores)
# [ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


In [109]:

lovescore2 = love_scores.reshape(10, 1)
lovescore3 = abs(lovescore2 - love_scores)
print(lovescore3)

[[ 0.   44.08 82.27 88.65 75.38 65.11 31.44 46.99  1.11 55.19]
 [44.08  0.   38.19 44.57 31.3  21.03 12.64  2.91 45.19 11.11]
 [82.27 38.19  0.    6.38  6.89 17.16 50.83 35.28 83.38 27.08]
 [88.65 44.57  6.38  0.   13.27 23.54 57.21 41.66 89.76 33.46]
 [75.38 31.3   6.89 13.27  0.   10.27 43.94 28.39 76.49 20.19]
 [65.11 21.03 17.16 23.54 10.27  0.   33.67 18.12 66.22  9.92]
 [31.44 12.64 50.83 57.21 43.94 33.67  0.   15.55 32.55 23.75]
 [46.99  2.91 35.28 41.66 28.39 18.12 15.55  0.   48.1   8.2 ]
 [ 1.11 45.19 83.38 89.76 76.49 66.22 32.55 48.1   0.   56.3 ]
 [55.19 11.11 27.08 33.46 20.19  9.92 23.75  8.2  56.3   0.  ]]


In [112]:
np.abs(love_scores[:, np.newaxis] - love_scores)

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11,
        55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19,
        11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38,
        27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76,
        33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49,
        20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,
         9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55,
        23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,
         8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  ,
        56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,
         0.  ]])

In [118]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/intermediate/professor-prick/
import numpy as np

generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))

dem = 0
for i in range(0, len(scores)):
    if scores[i] <= 60: 
        scores[i] = 0
        dem += 1
    if dem == 3: 
        break
print(scores)
# [68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]

[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [123]:
below_60 = np.where(scores <= 60)[0]
scores[below_60][:3]
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

In [ ]:
# Source: https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/
import numpy as np

field = np.zeros(shape = (10, 10))

print(field)
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
ran_pos = np.random.choice(field.size, size = 20, replace = False)
ran_val = np.random.normal(loc = 0, scale = 1, size = 20)
# print(ran_val)
field.ravel()[ran_pos] = ran_val
print(ran_pos)
